name: Python Sidebar Auto-Gen

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Generator
        run: python sidebar_gen.py

      - name: Commit and Push
        run: |
          git config --global user.name "Solus Bot"
          git config --global user.email "bot@solus.wiki"
          git add _sidebar.md
          git commit -m "Auto-sidebar (Python) [skip ci]" || exit 0
          git push
