name: Auto-Sidebar Generator

on:
  push:
    branches:
      - main  # Vérifie que c'est bien le nom de ta branche principale
    paths:
      - '**.md'
      - 'generate_sidebar.py'

jobs:
  update-sidebar:
    runs-on: ubuntu-latest
    
    # Autorise l'Action à écrire dans le dépôt
    permissions:
      contents: write

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🐍 Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: ⚙️ Génération de la sidebar
        run: python generate_sidebar.py

      - name: 🚀 Commit et Push des changements
        run: |
          git config --global user.name "Solus-Bot"
          git config --global user.email "bot@solus.wiki"
          git add _sidebar.md
          # On vérifie s'il y a des changements avant de commit pour éviter une erreur
          if git diff --staged --quiet; then
            echo "Aucune modification détectée sur la sidebar."
          else
            git commit -m "docs: mise à jour automatique de la sidebar [skip ci]"
            git push
          fi
